# Docker compose file for local development

version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file: .env

  database:
    image: postgres:14
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 5
    env_file:
      - .database.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend-migrate:
    build: .
    depends_on:
      database:
        condition: service_healthy
    entrypoint: [ "alembic", "upgrade", "head" ]
    env_file: .env


  celery:
    build: .
    depends_on: [ redis, backend ]
    entrypoint: "celery -A core.celery_app.celery worker --loglevel=info"
    env_file:
      - .env

  redis:
    image: redis:6

volumes:
  postgres-data:
