"""create transcation table

Revision ID: 6ac1c1c54be6
Revises: 
Create Date: 2022-05-21 23:48:57.318788

"""
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "6ac1c1c54be6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("seller_wallet", sa.String(), nullable=True),
        sa.Column("buyer_wallet", sa.String(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "ON_PAYMENT_WAIT",
                "ON_APPROVE",
                "EXPIRED",
                "SUCCESS",
                "CANCELED",
                name="transactionstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "crypto_type",
            sa.Enum("ERC20", "ETH", name="cryptotype"),
            nullable=False,
        ),
        sa.Column("initiator", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("closed_on", sa.DateTime(), nullable=True),
        sa.Column("hash", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transaction_buyer_wallet"),
        "transaction",
        ["buyer_wallet"],
        unique=False,
    )
    op.create_index(op.f("ix_transaction_hash"), "transaction", ["hash"], unique=True)
    op.create_index(
        op.f("ix_transaction_seller_wallet"),
        "transaction",
        ["seller_wallet"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transaction_initiator"),
        "transaction",
        ["initiator"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transaction_initiator"), table_name="transaction")
    op.drop_index(op.f("ix_transaction_seller_wallet"), table_name="transaction")
    op.drop_index(op.f("ix_transaction_hash"), table_name="transaction")
    op.drop_index(op.f("ix_transaction_buyer_wallet"), table_name="transaction")
    op.drop_table("transaction")
    # ### end Alembic commands ###
