"""sell type added

Revision ID: 2ed50c4780ec
Revises: 1312b3fcc59d
Create Date: 2022-05-30 22:32:44.997333

"""
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

from alembic import op
from db.models.transaction import SellType

revision = "2ed50c4780ec"
down_revision = "1312b3fcc59d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sell_types = postgresql.ENUM(SellType, name="selltype")
    sell_types.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "transaction",
        sa.Column(
            "sell_type",
            sa.Enum("SELL", "BUY", name="selltype"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sell_types = postgresql.ENUM(SellType, name="selltype")
    sell_types.drop(op.get_bind())
    op.drop_column("transaction", "sell_type")
    # ### end Alembic commands ###
