"""added email fields

Revision ID: d45629071765
Revises: 6ac1c1c54be6
Create Date: 2022-05-23 19:29:28.980880

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d45629071765"
down_revision = "6ac1c1c54be6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transaction", sa.Column("seller_email", sa.String(), nullable=True))
    op.add_column("transaction", sa.Column("buyer_email", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_transaction_buyer_email"),
        "transaction",
        ["buyer_email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transaction_seller_email"),
        "transaction",
        ["seller_email"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transaction_seller_email"), table_name="transaction")
    op.drop_index(op.f("ix_transaction_buyer_email"), table_name="transaction")
    op.drop_column("transaction", "buyer_email")
    op.drop_column("transaction", "seller_email")
    # ### end Alembic commands ###
