"""fiat data and updated_at

Revision ID: 1312b3fcc59d
Revises: 6ac1c1c54be6
Create Date: 2022-05-28 16:07:12.462969

"""
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

from alembic import op
from db.models.transaction import FiatType

revision = "1312b3fcc59d"
down_revision = "6ac1c1c54be6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    fiat_types = postgresql.ENUM(FiatType, name="fiattype")
    fiat_types.create(op.get_bind(), checkfirst=True)
    op.add_column("transaction", sa.Column("seller_email", sa.String(), nullable=False))
    op.add_column("transaction", sa.Column("buyer_email", sa.String(), nullable=False))
    op.add_column(
        "transaction",
        sa.Column("fiat_amount", sa.Numeric(precision=14, scale=6), nullable=False),
    )
    op.add_column(
        "transaction",
        sa.Column("fiat_type", fiat_types, nullable=False),
    )
    op.add_column("transaction", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.create_index(
        op.f("ix_transaction_buyer_email"),
        "transaction",
        ["buyer_email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transaction_seller_email"),
        "transaction",
        ["seller_email"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    fiat_types = postgresql.ENUM(FiatType, name="status")
    fiat_types.drop(op.get_bind())
    op.drop_index(op.f("ix_transaction_seller_email"), table_name="transaction")
    op.drop_index(op.f("ix_transaction_buyer_email"), table_name="transaction")
    op.drop_column("transaction", "updated_at")
    op.drop_column("transaction", "fiat_type")
    op.drop_column("transaction", "fiat_amount")
    op.drop_column("transaction", "buyer_email")
    op.drop_column("transaction", "seller_email")
    # ### end Alembic commands ###
